### ISSUE TITLE
The POM for com.tonikelope.coronahmac:coronahmac:jar:1.1.24 is missing, no dependency information available

### ISSUE THREAD

**Issue by yurivict** [tonikelope/coronapoker#3]
This command that the FreeBSD port runs to build ```coronapoker``` fails:

/usr/bin/env XDG_DATA_HOME=/usr/ports/games/coronapoker/work XDG_CONFIG_HOME=/usr/ports/games/coronapoker/work HOME=/usr/ports/games/coronapoker/work PATH=/usr/ports/games/coronapoker/work/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin NO_PIE=yes MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES PREFIX=/usr/local LOCALBASE=/usr/local CC=cc CFLAGS=-O2 -pipe -fno-omit-frame-pointer  -fstack-protector-strong -fno-strict-aliasing  CPP=cpp CPPFLAGS=-fno-omit-frame-pointer LDFLAGS= -fstack-protector-strong  LIBS= CXX=c++ CXXFLAGS=-O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer   MANPREFIX=/usr/local BSD_INSTALL_PROGRAM=install  -s -m 555 BSD_INSTALL_LIB=install  -s -m 0644 BSD_INSTALL_SCRIPT=install  -m 555 BSD_INSTALL_DATA=install  -m 0644 BSD_INSTALL_MAN=install  -m 444 JAVA_HOME=/usr/local/openjdk11 /usr/local/bin/mvn -fae install -Dmaven.test.skip=true -Duser.home=/usr/ports/games/coronapoker/work package

```
[WARNING] The POM for com.tonikelope.coronahmac:coronahmac:jar:1.1.24 is missing, no dependency information available
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.368 s
[INFO] Finished at: 2021-02-26T19:27:04-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project CoronaPoker: Could not resolve dependencies for project com.tonikelope:CoronaPoker:jar:FINAL-7.36: Could not find artifact com.tonikelope.coronahmac:coronahmac:jar:1.1.24 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

Older versions were building fine with the same command.

FreeBSD 12.2

**Comment by tonikelope** [comment]
coronahmac is not uploaded to the central maven repository. In order to build coronapoker you need to add coronahmac as a local Maven repository first.

To do so:

`mvn install:install-file -Dfile=/path/to/coronaHMAC_x.x.x.jar -DgroupId=com.tonikelope.coronahmac -DartifactId=coronahmac -Dversion=x.x.x -Dpackaging=jar`

After this is done, the project can be built as usual.

Regards.

**Comment by yurivict** [comment]
```coronaHMAC_x.x.x.jar``` is closed source, so nobody really knows what is in it.

I am inclined to think that closed source software is security risk because it tries to make me trust parties who I don't have any knowledge about.

**Comment by tonikelope** [comment]
Hi. Agree. I will put ASAP the instructions to be able to compile the game
using mvn without including that dependency although logically that
functionality will be lost.

Regates.

**Comment by tonikelope** [comment]
README UPDATED -> https://github.com/tonikelope/coronapoker
